{% set name = "numcodecs" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05d91a433733e7eef268d7e80ec226a0232da244289614a8f3826901aec1098e

build:
  number: 1
  script_env:
    - DISABLE_NUMCODECS_AVX2=""
    - DISABLE_NUMCODECS_SSE2=""  # [not x86]
  script:
    - export CFLAGS="${CFLAGS} -pthread"  # [aarch64 or ppc64le]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools >=64
    - setuptools_scm >=6.2
    - tomli
    - py-cpuinfo
  run:
    - python
    - numpy >=1.7
    - msgpack-python

test:
  requires:
    - coverage
    - flake8
    - pytest
    - pytest-cov
    - pip
    - importlib_metadata
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pip check
    - pytest -v --pyargs numcodecs

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE.txt
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - joshmoore
    - jrbourbeau
