{% set name = "numcodecs" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba4fac7036ea5a078c7afe1d4dffeb9685080d42f19c9c16b12dad866703aa2e
  patches:
    ################################################################
    # Revert NumPy build dependency                                #
    #                                                              #
    # xref: https://github.com/zarr-developers/numcodecs/pull/557  #
    ################################################################
    - patches/PR_557.patch

build:
  number: 0
  skip: true  # [py<310]
  script_env:
    - DISABLE_NUMCODECS_AVX2=""
    - DISABLE_NUMCODECS_SSE2=""  # [not x86]
  script:
    - export CFLAGS="${CFLAGS} -pthread"  # [aarch64 or ppc64le]
    - mkdir builddir
    - {{ PYTHON }} -m build --wheel --no-isolation --skip-dependency-check -Cbuilddir=builddir
    - {{ PYTHON }} -m pip install --find-links dist {{ name }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - python-build
    - numpy
    - pip
    - cython
    - setuptools >=64
    - setuptools_scm >=6.2
    - tomli
    - py-cpuinfo
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - msgpack-python

test:
  requires:
    - coverage
    - flake8
    - pytest
    - pytest-cov
    - pip
    - importlib_metadata
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pip check
    - pytest -v --pyargs numcodecs

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE.txt
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - joshmoore
    - jrbourbeau
