{% set name = "numcodecs" %}
{% set version = "0.7.2" %}
{% set sha256 = "4a038064d5604e6181a64db668d7b700d9ae87e4041984c04cbf0042469664b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools >18.0
    - setuptools_scm >1.5.4
  run:
    - python
    - numpy >=1.7
    - msgpack-python

test:
  requires:
    - pytest
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pytest -v --pyargs numcodecs

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jrbourbeau
