{% set name = "numcodecs" %}
{% set version = "0.6.0" %}
{% set sha256 = "7144d293627d6317a4ac17836693117f52f74ff997fcd9eb2348b78ede359866" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - setuptools
    - setuptools_scm
  run:
    - python
    - numpy
    - msgpack-python
    - backports.lzma  # [py27]

test:
  requires:
    - pytest
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pytest -v --pyargs numcodecs

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
