{% set name = "numcodecs" %}
{% set version = "0.6.4.dev55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/zarr-developers/numcodecs
  git_rev: 7f28815870dbdedf126486d72b78506c2886ff73

build:
  number: 0
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - setuptools_scm
  run:
    - python
    - numpy
    - msgpack-python
    - backports.lzma  # [py27]

test:
  requires:
    - pytest
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pytest -v --pyargs numcodecs

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
