{% set name = "numcodecs" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22838c6b3fd986bd9c724039b88870057f790e22b20e6e1cbbaa0de142dd59c4
  patches:
    # this patch can be dropped in the next release
    - backport_369.patch

build:
  number: 1
  skip: true  # [py<=36]
  script:
    # The next two lines can be dropped in the next release.
    - rm numcodecs/*.c  # [not win]
    - del /f numcodecs\*.c  # [win]
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - export DISABLE_NUMCODECS_SSE2=""  # [arm64 or aarch64 or ppc64le]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - export CFLAGS="${CFLAGS} -pthread"  # [aarch64 or ppc64le]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools >18.0
    - setuptools_scm >1.5.4
  run:
    - python
    - entrypoints
    - numpy >=1.7
    - msgpack-python
    - typing-extensions >=3.7.4

test:
  requires:
    - pytest
    - pip
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pytest -v --pyargs numcodecs
    - pip check

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - joshmoore
    - jrbourbeau
