{% set name = "numcodecs" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6388e5f4e94d18a7165fbd1c9d3637673b74157cff8bc644005f9e2a4c717d6e

build:
  number: 0
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - export DISABLE_NUMCODECS_SSE2=""  # [arm64 or aarch64 or ppc64le]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - export CFLAGS="${CFLAGS} -pthread"  # [aarch64 or ppc64le]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools >=64
    - setuptools_scm >=6.2
    - tomli
    - py-cpuinfo
  run:
    - python
    - numpy >=1.7
    - msgpack-python

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
    - pip
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pytest -v --pyargs numcodecs
    - pip check

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE.txt
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - joshmoore
    - jrbourbeau
