{% set name = "numcodecs" %}
{% set version = "0.8.0" %}
{% set sha256 = "7c7d0ea56b5e2a267ae785bdce47abed62829ef000f03be8e32e30df62d3749c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Update-cpuinfo-to-8.0.0.patch  # [arm64]

build:
  number: 0
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - export DISABLE_NUMCODECS_SSE2=""  # [arm64]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools >18.0
    - setuptools_scm >1.5.4
  run:
    - python
    - numpy >=1.7
    - msgpack-python

test:
  requires:
    - pytest
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pytest -v --pyargs numcodecs

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jrbourbeau
