{% set name = "numcodecs" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2dd42564e7772a9385923b02a363e3cedf053ce93094a9064485e7f69a6f1c92

build:
  number: 1
  skip: true  # [py<=36]
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - export DISABLE_NUMCODECS_SSE2=""  # [arm64 or aarch64 or ppc64le]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - export CFLAGS="${CFLAGS} -pthread"  # [aarch64 or ppc64le]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools >18.0
    - setuptools_scm >1.5.4
  run:
    - python
    - numpy >=1.7
    - msgpack-python
    - typing-extensions >=3.7.4
    # optional dependency
    - entrypoints

test:
  requires:
    - pytest
    - pip
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pytest -v --pyargs numcodecs
    - pip check

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - joshmoore
    - jrbourbeau
