appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Tr9v7C3aK7C3uI7St7GmSQ3Pwb50mEg7EsRYu7oiL28LSLuk9w/30J0MAFX4lMA1YSvf+ylFn2MDf+wivJFdsfV6U4LTTejEQ8fDzmEie90WMukUpt7RGmlrpMUQ9K/2V2zO9KNc7XgchftO4xPVJF2d9FoFPYp0+8A+w8uT+p+hl0bIlMWvza59OUdQM5py29Bq4UEB0r0ZBs86HLVjTtINAUX3rP1tF0b2InwXrmO6JavjGC2xX1saEgN//1z1p1mheRzcgqNKFwehKtEMcQlpxvLe2/ukshXmlz2kQTvEOlvyrKPQpKS0sRxS2XtGJKOEZn89QNt5quRMxxlH7+d7oNRPMhibUMkmOedGuipwCLMLr41UFUzY9/dF3SdGkukL7k+D1NRAbb5cZ10qUvXjBZa+XccU/sC4yUODuubIXoi8wY82eMsflu86lgDqByr7Gbuw16LqgBxuoaYBW75yzB9KfbNpVz4mnONTu9nCDJSXLhUeVy+CNNbrvgv6GratenufTFIvDUY3X5Hj/M25qvBH/hocem7g25yJ8Sf+v1VjcvRtSTruIChoPhmLmldwHA9JdJk9h1xokBqBoYZXkoAehUBos0TRa/z58XtqwYf5XjxDdWtKwbxd1m2NZPsp+DDZQXw9NaTFu9yvrSe3M+5wgvV2VXK3ydFIkfo=}
